### ISSUE TITLE
[MODULE REQUEST]

### ISSUE THREAD

**Issue by MarioC3** [owlnai/isnuxt3ready#11]
- **Module name in NPM**:
- nuxt-extend
- **Does it work with Nuxt Bridge?**:
- I don't think so
- **Does it work with Nuxt 3?**:
- No
- **Maintainers, if any**:
- pi0
- **GitHub related issue URL, if any**:
- Here's the RFC that says they will put it in directly on Nuxt 3: https://github.com/nuxt/rfcs/issues/30
- **GitHub repository URL, if any**:
- https://github.com/nuxt-community/nuxt-extend

**Comment by owlnai** [comment]
![image](https://user-images.githubusercontent.com/20427094/138732056-fca3b808-9bef-476e-b006-04cd3425cef6.png)
Added, thanks a lot! 😄

**Comment by MarioC3** [comment]
You da man!
