### ISSUE TITLE
[MODULE REQUEST]

### ISSUE THREAD

**Issue by ghost** [owlnai/isnuxt3ready#12]
- **Module name in NPM**:  nuxt-buefy
- **Does it work with Nuxt Bridge?**: Haven't tested it.
- **Does it work with Nuxt 3?**: No.
- **Maintainers, if any**:
- **GitHub related issue URL, if any**:
- **GitHub repository URL, if any**:

**Comment by owlnai** [comment]
![image](https://user-images.githubusercontent.com/20427094/138782056-e1a77c57-eb1f-4239-9dc8-c42bf9fdfa11.png)
Added thanks!
