### ISSUE TITLE
[MODULE REQUEST] @nuxtjs/web-vitals

### ISSUE THREAD

**Issue by Suya1671** [owlnai/isnuxt3ready#13]
- **Module name in NPM**: @nuxtjs/web-vitals
- **Does it work with Nuxt Bridge?**: NOT TESTED
- **Does it work with Nuxt 3?**:  Doesnt seem to. Nothing reported to Vercel dashboard
- **Maintainers, if any**: https://github.com/nuxt-community/web-vitals-module/graphs/contributors
- **GitHub related issue URL, if any**:  Maybe nuxt-community/web-vitals-module#23
- **GitHub repository URL, if any**: https://github.com/nuxt-community/web-vitals-module

**Comment by owlnai** [comment]
![image](https://user-images.githubusercontent.com/20427094/139100769-39760765-9ccf-4bdd-b541-b49919374755.png)
Added, thanks!
