### ISSUE TITLE
[MODULE REQUEST] @nuxtjs/fontawesome

### ISSUE THREAD

**Issue by toniengelhardt** [owlnai/isnuxt3ready#14]
- **Module name in NPM**: @nuxtjs/fontawesome
- **Does it work with Nuxt Bridge?**: unknown
- **Does it work with Nuxt 3?**: unknown
- **Maintainers, if any**:
- **GitHub related issue URL, if any**:
- **GitHub repository URL, if any**:

**Comment by owlnai** [comment]
![image](https://user-images.githubusercontent.com/20427094/139100681-ccdda8ec-aa1b-412f-9dba-1d294aeabc33.png)
Added, thanks!
