### ISSUE TITLE
[MODULE REQUEST] @nuxtjs/moment

### ISSUE THREAD

**Issue by Eliophot** [owlnai/isnuxt3ready#15]
- **Module name in NPM**: @nuxtjs/moment
- **Does it work with Nuxt Bridge?**: NOT TESTED
- **Does it work with Nuxt 3?**: Nope https://github.com/nuxt-community/moment-module/issues/82
- **Maintainers, if any**: https://github.com/nuxt-community/moment-module/graphs/contributors
- **GitHub related issue URL, if any**: https://github.com/nuxt-community/moment-module/issues
- **GitHub repository URL, if any**: https://github.com/nuxt-community/moment-module

**Comment by owlnai** [comment]
![image](https://user-images.githubusercontent.com/20427094/139100559-2b2abb11-cb50-4891-8ed2-e760eab406af.png)
Added, thanks!
