### ISSUE TITLE
[MODULE REQUEST] @nuxtjs/robots

### ISSUE THREAD

**Issue by Eliophot** [owlnai/isnuxt3ready#16]
- **Module name in NPM**: @nuxtjs/robots
- **Does it work with Nuxt Bridge?**: NOT TESTED
- **Does it work with Nuxt 3?**: Nope
- **Maintainers, if any**: https://github.com/nuxt-community/robots-module/graphs/contributors 
- **GitHub related issue URL, if any**: https://github.com/nuxt-community/robots-module/issues
- **GitHub repository URL, if any**: https://github.com/nuxt-community/robots-module

**Comment by owlnai** [comment]
![image](https://user-images.githubusercontent.com/20427094/139100486-045e95df-bea3-4ccf-9a3f-180869ecb54e.png)
Added, thanks!
