### ISSUE TITLE
Migration to nuxt/modules

### ISSUE THREAD

**Issue by pi0** [owlnai/isnuxt3ready#17]
Hi @owlnai  ✋ 

As promised, the modules database is now updated with compatibility metadata.

You can read about usage here: https://github.com/nuxt/modules#modules-database 

Also, it would be nice if we change issue creating a link to target nuxt/modules 💚

**Comment by owlnai** [comment]
Hi @pi0, that's great to hear 👏 

From what I've seen, everything here is already covered by https://modules.nuxtjs.org/, so maybe it's best to archive this repository and redirect to nuxt/modules to avoid duplication 😄

**Comment by pi0** [comment]
Sure that would be amazing if we can join forces to make a single beautiful website together 💯 (feel free to close my issue then)

**Comment by owlnai** [comment]
Joining forces would be a pleasure! Let me know if I can be of any help 💪  

I'll add a migration banner later. My idea is keeping this site up for some time as it's been linked from some sites, then a 301 redirect to https://modules.nuxtjs.org.

**Comment by atinux** [comment]
Thank you @owlnai 

Your help is more than welcome to add same features as you have (filters).

I definitely need a way to show all the awesome contributors like you 💚
